name: subman
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-394.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.1.1
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^13.0.4
  firebase_storage: ^10.3.4
  firebase_core_platform_interface: 4.5.1
  cloud_firestore: ^3.5.1
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.4
  google_sign_in: ^5.4.2
  firebase_analytics: ^9.3.8
  the_apple_sign_in: ^1.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/logo.png
    - assets/apple.png

    - assets/logos/spotify.png
    - assets/logos/apple.png
    - assets/logos/icloud.png
    - assets/logos/netflix.png
    - assets/logos/spotify_alt.png
    - assets/logos/apple_alt.png
    - assets/logos/icloud_alt.png
    - assets/logos/netflix_alt.png
    - assets/logos/other.png
    - assets/logos/aws.png
    - assets/logos/aws_alt.png
    - assets/logos/american_express.png
    - assets/logos/american_express_alt.png
    - assets/logos/slack.png
    - assets/logos/slack_alt.png
    - assets/logos/playstation.png
    - assets/logos/playstation_alt.png
    - assets/logos/google_drive.png
    - assets/logos/google_drive_alt.png
    - assets/logos/apple_one.png
    - assets/logos/apple_one_alt.png
    - assets/logos/paetron.png
    - assets/logos/paetron_alt.png
    - assets/logos/amazon_prime.png
    - assets/logos/amazon_prime_alt.png
    - assets/logos/prime_video.png
    - assets/logos/prime_video_alt.png

    - assets/settings/box.png
    - assets/settings/file.png
    - assets/settings/fingerprint.png
    - assets/settings/money.png
    - assets/settings/star.png
    - assets/settings/categories.png

 
  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SFP-Regular.otf
        - asset: fonts/SFP-Bold.otf

